services:
  rest-service:
    build: .  # Dockerfile im aktuellen Verzeichnis verwenden
    ports:
      - "8080:8080"  # REST-Service erreichbar auf Port 8080
    networks:
      - monitoring

  node-exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"
    networks:
      - monitoring
  prometheus:
    image: prom/prometheus
    volumes:
      - ./alert.rules.yml:/etc/prometheus/alert.rules.yml
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus  # Persistente Daten
    ports:
      - "9090:9090"  # Prometheus UI auf Port 9090
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - "--web.enable-lifecycle" # um Prometheus zur Laufzeit zu aktualisieren
      - '--storage.tsdb.retention.time=7d'
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"  # Grafana UI
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=4351
    volumes:
      - grafana_data:/var/lib/grafana # sichert Dashboards
    networks:
      - monitoring
    depends_on:
      - prometheus


networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data: