services:
  rest-service:
    build: .  # Dockerfile im aktuellen Verzeichnis verwenden
    ports:
      - "8080:8080"  # REST-Service erreichbar auf Port 8080
    networks:
      - monitoring

  node-exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"
    networks:
      - monitoring
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus  # Persistente Daten
    ports:
      - "9090:9090"  # Prometheus UI auf Port 9090
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - "--web.enable-lifecycle"
      - '--storage.tsdb.retention.time=7d'
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data: